apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: node171629224
  janus-idp.io/tekton: node171629224
  backstage.io/kubernetes-id: node171629224
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: node171629224
resources:
- deployment.yaml
- route.yaml
- service.yaml
