apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: node171629224
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node171629224 
  name: node171629224
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: node171629224 
